# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:clusterrole
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "clusterbackup.name" . }}
    chart: {{ template "clusterbackup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "clusterbackup.name" . }}
    helm.sh/chart: {{ template "clusterbackup.chart" . }}
    component: clusterrole

rules:

- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create

- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - watch

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - get
  - list
  - watch

- verbs:
  - list
  - get
  apiGroups:
  - ''
  resources:
  - secrets

- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - channels
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch

- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores
  - backups
  - backupschedules

- verbs:
  - update
  apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores/finalizers
  - backups/finalizers
  - backupschedules/finalizers

- verbs:
  - get
  - patch
  - update
  apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - restores/status
  - backups/status
  - backupschedules/status

- verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
  apiGroups:
  - velero.io
  resources:
  - backups
  - restores
  - schedules

- apiGroups:
  - velero.io
  resources:
  - deletebackuprequests
  verbs:
  - create
  - list
  - watch
