# Copyright Contributors to the Open Cluster Management project

# Default values for cluster_backup-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

org: open-cluster-management

global:
  pullPolicy: Always
  imageOverrides:
    cluster_backup: ""
  certificateAuthority:
    issuer: multicloud-ca-issuer
    kind: Issuer

hubconfig:
  nodeSelector: null
  replicaCount: 1

pullSecret: null
arch:
- amd64
- ppc64le
- s390x

enabled: true

clusterbackup:
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
